name: Website Update

on:
  schedule:
    - cron: '0 14 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: npm install
        working-directory: builder
      - run: npm start
        working-directory: builder
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_SECRET }}
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_PASS: ${{ secrets.REDDIT_PASS }}
